### ISSUE TITLE
Which method  of world to camera coord is recommended?

### ISSUE THREAD

**Issue by zc-alexfan** [facebookresearch/InterHand2.6M#107]
I noticed that you have two ways to convert from world to camera coordinate for MANO joints. Which one do you recommend? (a bit confused as two methods are provided)

1. MANO in world -> joints in world -> joints in cam
2. MANO in world -> MANO in cam -> joints in cam

Thanks

**Comment by mks0601** [comment]
The reason why I provided two methods is that someone might need MANO parameters in the camera coordinate system.
If you need only 3D mesh coordinates without MANO parameters, you can use whatever you want.
