### ISSUE TITLE
Comparison

### ISSUE THREAD

**Issue by ZhengdiYu** [facebookresearch/InterHand2.6M#108]
Hi, I was wondering why some works (including your Interhand2.6M) do not compare with: (CVPR2019) 3D Hand Shape and Pose Estimation from a Single RGB Image, Liuhao Ge. (https://docs.google.com/viewer?a=v&pid=sites&srcid=ZGVmYXVsdGRvbWFpbnxnZWxpdWhhb250dXxneDo3ZjE0ZjY3OWUzYjJkYjA2)

I saw this work has results on RHD and STB as well

**Comment by mks0601** [comment]
Thanks for letting me know. I know this work, but the important thing of this work is 3D interacting hand pose, not 3D single hand pose. RHD and STB are 3D single hand pose datasets.

**Comment by ZhengdiYu** [comment]
> Thanks for letting me know. I know this work, but the important thing of this work is 3D interacting hand pose, not 3D single hand pose. RHD and STB are 3D single hand pose datasets.

Thanks for your reply, but I think this work has better performance that the second last one in your table.

Anyway, I have another question: https://arxiv.org/pdf/2005.04551.pdf (epipolar transformer) It seems that the MPJPE of 'InterHand dataset'is very low in this paper, have you tested this in your finally released InterHand2.6M?

**Comment by mks0601** [comment]
Epipolar transformer paper is from the same group, but the 'InterHand dataset' of that paper is totally different from our InterHand2.6M. Actually, that paper is presented (CVPR 2020) before our InterHand2.6M dataset is released (ECCV 2020).
Lastly, Epipolar transformer takes mulit-view calibrated images as an input, while ours takes a single rgb image as an input.

**Comment by ZhengdiYu** [comment]
Thanks for your clarification!
