### ISSUE TITLE
label is  wrong 

### ISSUE THREAD

**Issue by yunshangyue71** [facebookresearch/InterHand2.6M#113]
"/media/q/data/dataset/InterHand2.6M/InterHand2.6M/InterHand2.6M_5fps_batch1/images/train/Capture25/0282_sarcasticclap/cam410018/image52725.jpg"
this image contain double hand , but the label  only one hand ,
![2022-04-27 12-00-30 的屏幕截图](https://user-images.githubusercontent.com/43103939/165437981-a9db6c6d-a8d1-43da-ab17-e002b290e5d7.png)

**Comment by mks0601** [comment]
Please check joint_valid as well. There are some joints that are not annotated due to the annotation failure.

**Comment by yunshangyue71** [comment]
ok
