### ISSUE TITLE
how to convert 2.5D coordinate to real-world 3D coordinate?

### ISSUE THREAD

**Issue by Joyako** [facebookresearch/InterHand2.6M#115]
Hi, thanks for your excellent project! 
Q1: What coordinate system is the output of the model directly? 
Q2: I found in your paper 4.4 how the 3D coordinates of the hand are calculated as fllows:
<img width="669" alt="截屏2022-05-11 上午10 18 34" src="https://user-images.githubusercontent.com/25999552/167755680-081c49c9-da89-4f4e-864a-87a999cf2005.png">
but I can not understand that what the meaning of camera back-projection and inverse affine transformation and how to calculate it in your code.
Looking forward to your reply, thanks.

**Comment by mks0601** [comment]
Q1. x,y: pixel (0~63, 0~63), z: depth (normalized to 0~64)
Q2. camera back-projection: (x_img, y_img, z_real) -> (x_real, y_real, z_real). inverse affine transformation: cropped and resized hand image space -> original image space before cropping and resizing

**Comment by Joyako** [comment]
@mks0601 thanks a lot,  assuming that the camera internal parameters are known , how to use (x_img, y_img, z_real) to get (x_real, y_real, z_real),  generally like this:
<img width="316" alt="截屏2022-05-11 下午1 04 31" src="https://user-images.githubusercontent.com/25999552/167772883-e3baf3a9-6264-418c-90a5-fcae0f2ddfca.png">
but there is a z_real(x_img, y_img, z_real), are there any other formulas to solve camera back-projection?

**Comment by Joyako** [comment]
@mks0601 thanks a lot, 
camera back-projection:  (x_img, y_img, z_real) -> (x_real, y_real, z_real)
Assuming that the camera internal parameters are know , it can be solved by the following formula, right?
z_real = z_real
x_real = (x_img - cx) * z_real / fx
y_real = (y_img - cy) * z_real / fy

camera internal parameters:
K = [[fx, 0, cx], [0, fy, cy], [0, 0, 1]]

**Comment by mks0601** [comment]
yes. that function is implemented in utils.transformations.pixel2cam

**Comment by Joyako** [comment]
thanks, I will close it.
