### ISSUE TITLE
Is there a way to transform the results to original image?

### ISSUE THREAD

**Issue by ZhengdiYu** [facebookresearch/InterHand2.6M#117]
Hi, I was wondering that is there a way to transform the results to original image? Because all the rendering visualizations are based on the cropped image

**Comment by mks0601** [comment]
You mean visualization of 3D meshes? or 3D keypoints?

**Comment by ZhengdiYu** [comment]
> You mean visualization of 3D meshes? or 3D keypoints?

Both of them. But now I'm working on mesh. Thanks for your quick reply! I want to vis your mesh on original image

**Comment by mks0601** [comment]
Have you tried this demo?
https://github.com/facebookresearch/InterHand2.6M/blob/main/tool/MANO_render/render.py
It renders mesh on the original image (not on a cropped image)

**Comment by ZhengdiYu** [comment]
Yep, I've tried this before. I think I miss something, I actually want something to transfer the prediction on 256 to (512, 334). It seems that the 'inv_trans' is what I want, right?

**Comment by mks0601** [comment]
Correct. For the mesh visualization, you can follow the demo code. For the keypoint visualization, you should use inv_trans.

**Comment by ZhengdiYu** [comment]
Thanks. By the way, if I instead have meshes on 256 size image, rather than keypoints. Could I use the same code for it?

**Comment by ZhengdiYu** [comment]
I think the inv_trans is directly moving the projected 2d keypoints, am I understanding correctly?

**Comment by mks0601** [comment]
> Thanks. By the way, if I instead have meshes on 256 size image, rather than keypoints. Could I use the same code for it?

You should modify camera intrinsics to render meshes of 256 size image to the original image.
For example, focal_x= focal_x / 256 * bbox_width, princpt_x = princpt_x / 256 * bbox_width + bbox_x_min
Then, you can use the same code.

**Comment by mks0601** [comment]
They are the smae. trans_point2d is actually an old function and the batched version is a updated one.

**Comment by ZhengdiYu** [comment]
> They are the same. `trans_point2d` is actually an old function and the batched version is a updated one.

Thank you so much! That is really helpful. It solves one of my old question. Great job! Close now.
