### ISSUE TITLE
How to transform 3D joints set to MANO angle axis representation?

### ISSUE THREAD

**Issue by Maradowei** [facebookresearch/InterHand2.6M#123]
I want to know How to transform 3D joints set to MANO angle axis representation? thanks.

**Comment by mks0601** [comment]
As I said in the earlier issue, you cannot directly transform as it is an ill-posed problem. This is called inverse kinematics. Please read my paper (NeuralAnnot), which is used to obtain MANO parameters of this dataset.

**Comment by Maradowei** [comment]
Thanks very much.

**Comment by Maradowei** [comment]
I think I don't know what the 45 hand pose parameters (angle axis) mean. I compute each angle axis of 3 points from 21 3D joints following the kinematic tree. For example, I compute the angle axis of Vector(J0->J1) and Vector(J1->J2), and I stacked the 15 angle axis as the mano parameter. And I set random shape parameters, but the resulting mesh looks weird.

**Comment by mks0601** [comment]
You'd better study 6 dof. You cannot get twist rotation from points

**Comment by Maradowei** [comment]
Tanks

**Comment by Maradowei** [comment]
V

**Comment by Maradowei** [comment]
Very sorry to interrupt again. I have got close 3D coordinates in the camera coordinate system somehow, and I want to use the joints to manually do something on mano parameters rather than just feed them in the network, I have used the root location to the trans parameter of mano and it seems good. Is there any way to use these joints manually? Thanks very much.
