### ISSUE TITLE
Multiple black images in dataset/ Mismatch between annotation id and image id

### ISSUE THREAD

**Issue by SalmaG98** [facebookresearch/InterHand2.6M#125]
Hello,

Thank you for your work!

I am evaluating a pose estimator on your dataset and I noticed there was number of black images for certain frames even though other views are okay, this means that there is an annotation for the said views in world coordinate system but the images are actually fully black which would penalize pose estimators in case of not detecting anything, are you aware of this or should I verify my download ?

**Comment by mks0601** [comment]
Yes I'm aware of that, but it is actually very hard to automatically detect such images perfectly.. I used some heuristics to filter such black images, but there might still be such images. As this dataset contains huge amount of images, I guess such images might affect the average error marginally.

**Comment by SalmaG98** [comment]
Okay thank you just wanted to make sure that this is not an issue with our download. 

I also have a separate question about annotations, I wrote my own pytorch dataloader for the dataset which respects the structure mentioned in [https://mks0601.github.io/InterHand2.6M/](url). I retrieve the ```image_id``` from the annotation I am reading and use it to retrieve the image path from the "images" dictionary in ```{split}_data.json``` . After a successful validation on a few sequences from Captures 0 in both the test and validation split my script crashes with this error:
```
File "/home/sgalaaou/src/SignLanguage/clustering/interhand_dataset.py", line 59, in __getitem__
    capture_id = self.image_list[image_id]['capture']
IndexError: list index out of range
```
Which means that some ```image_id``` present in the annotation dictionary is not found in the image dictionary. I don't know if my description makes sense (sorry if it doesn't) but have I misunderstood the structure of your annotations ?

**Comment by SalmaG98** [comment]
Okay thank you just wanted to make sure that this is not an issue with our download. 

I also have a separate question about annotations, I wrote my own pytorch dataloader for the dataset which respects the structure mentioned in [https://mks0601.github.io/InterHand2.6M/](url). I retrieve the ```image_id``` from the annotation I am reading and use it to retrieve the image path from the "images" dictionary in ```{split}_data.json``` . After a successful validation on a few sequences from Captures 0 in both the test and validation split my script crashes with this error:
```
File ".../interhand_dataset.py", line 59, in __getitem__
    capture_id = self.image_list[image_id]['capture']
IndexError: list index out of range
```
Which means that some ```image_id``` present in the annotation dictionary is not found in the image dictionary. I don't know if my description makes sense (sorry if it doesn't) but have I misunderstood the structure of your annotations ?

**Comment by mks0601** [comment]
For each annotation, there should be a corresponding image. Could you check with the dataloader in this repo and check again with your dataloader?

**Comment by SalmaG98** [comment]
Sorry this is an error from my side, I did see you recommend using pycocotools for the dataloading but I didn't think it was mandatory and since there is a discontinuity in annotation ids (maybe because you removed some annotations that weren't valid?), loading the ```{split}_data.json``` using just the json package returns lists for ```annotations``` and ```images``` for which the position of an entry in ```image_list``` doesn't necessarily correspond to the ```image_id``` (due to the discontinuity), this triggers the IndexError when I reach the end of the ```image_list``` I'm trying to index using ```image_id```. 

Changing only the loading of the ```{split}_data.json``` from json to pycocotools solves it because pycocotools constructs a dictionary whose keys correspond to ```id``` for both ```images``` and ```annotations```.

Thank you for you time and sorry for the inconvenience !
