### ISSUE TITLE
Difference between 30fps and 5fps model

### ISSUE THREAD

**Issue by toxicrecker** [facebookresearch/InterHand2.6M#135]
What's the difference between the 30fps model and the 5fps model if InterNet is supposed to be used on static images?

**Comment by mks0601** [comment]
You mean a difference between InterNet trained on 30 fps and 5 fps InterHand2.6M dataset?

**Comment by toxicrecker** [comment]
Yes.

**Comment by mks0601** [comment]
InterNet trained on 30 fps might perform slightly better as it is trained on more data

**Comment by toxicrecker** [comment]
Alright thank you!
