### ISSUE TITLE
About 3D joints

### ISSUE THREAD

**Issue by liangzhenghao2000** [facebookresearch/InterHand2.6M#136]
I passed the shape and pose parameters into the manolayer to calculate the 3D position of the Joints, and found that it was slightly different from the 3D position of the Joints in the data set. Most of the errors were at the millimeter level, but some reached the centimeter level.I want to know why.（All calculations are in camera coordinates, I aligned the wrist points of the two results）

**Comment by mks0601** [comment]
Because 3D positions of MANO joints are parameterized by MANO pose and shape parameters. On the other hand, 3D positions of joints of this dataset is directly regressed ones, not parameterized by any parameters.

**Comment by liangzhenghao2000** [comment]
> Because 3D positions of MANO joints are parameterized by MANO pose and shape parameters. On the other hand, 3D positions of joints of this dataset is directly regressed ones, not parameterized by any parameters.

So the joints3d in the data set are manually labeled or directly regressed, and the mano parameters are fitted based on these data?

**Comment by mks0601** [comment]
yeap. mano parameters are fitted using NeuralAnnot (https://openaccess.thecvf.com/content/CVPR2022W/ABAW/papers/Moon_NeuralAnnot_Neural_Annotator_for_3D_Human_Mesh_Training_Sets_CVPRW_2022_paper.pdf)

**Comment by liangzhenghao2000** [comment]
> yeap. mano parameters are fitted using NeuralAnnot (https://openaccess.thecvf.com/content/CVPR2022W/ABAW/papers/Moon_NeuralAnnot_Neural_Annotator_for_3D_Human_Mesh_Training_Sets_CVPRW_2022_paper.pdf)

Thanks！
