### ISSUE TITLE
About mano shape

### ISSUE THREAD

**Issue by liangzhenghao2000** [facebookresearch/InterHand2.6M#138]
The shapeirs of SMPLX's mano model are the same for the left and right hands(https://github.com/vchoutas/smplx/issues/48)，this leads that if we use the same shape parameter, the shapes of the left and right hands are asymmetrical，so I want to know which calculation method is used for this dataset when fitting the manoshape parameters，is there any processing for shapedirs?

**Comment by mks0601** [comment]
Hi, x-axis of shapedirs of the right/left hands should have the opposite direction as the x-axis of the template mesh of the right/left hands have the opposite direction.

**Comment by liangzhenghao2000** [comment]
Thanks，i saw you fix it in render.py line 27
