### ISSUE TITLE
test per batch

### ISSUE THREAD

**Issue by slava-smirnov** [facebookresearch/InterHand2.6M#14]
hey!

great work

Google Colab (GPU enabled) doesn't have enough space to download all of the images (40GB). Yet it’s tempting to try the whole thing. Can you possibly provide which of tar parts consist `test` split?

**Comment by slava-smirnov** [comment]
for future references. this is about v0.0 version of the dataset

**Comment by mks0601** [comment]
Hi, unfortunately, the images are uniformly splitted to zipped chunks. Maybe you can download images and upload test images to Google Colab server?

**Comment by slava-smirnov** [comment]
I guess yeah. That may work. Thanks for a workaround! Now the question would be how to proceed with 80gb for 5fps and 480gb of 30fps assuming resolution won't change

**Comment by ravitejageeda** [comment]
is it working in colab ?

**Comment by mks0601** [comment]
Sorry I haven't tested in colab
