### ISSUE TITLE
Different image size of 'cam400412'

### ISSUE THREAD

**Issue by jwzxgy2007** [facebookresearch/InterHand2.6M#157]
Thanks for your work! While processing the data, I discovered the image dimensions for cam400412 are 334x512, whereas the images from other cameras are 512x334. This discrepancy distorts the images in cam400412. I also noticed that the width recorded in the _data.json file is 512. Should I resize these images to the correct aspect ratio? Additionally, do the intrinsic and extrinsic parameters need to be modified as well?
![image20625](https://github.com/user-attachments/assets/01243aca-ef7d-4ca4-a922-0c2629f088b6)

**Comment by mks0601** [comment]
sorry for some wrong data. there could be such kind of wrong data, but the amount would be very small, so they might not affect the overall 3D errors on the entire test set. I guess you should modify the intrinsics, but could you check on your side?

**Comment by jwzxgy2007** [comment]
Thanks, I will check on my side
