### ISSUE TITLE
what are 4 views that used on Table 6 in paper?

### ISSUE THREAD

**Issue by donguk-dev** [facebookresearch/InterHand2.6M#16]
Thanks for your great research!

![image](https://user-images.githubusercontent.com/67183356/95172336-21792680-07f2-11eb-8656-06b00a3c98be.png)
Above image, what are 4 views trained ? (cam numbers like cam400004)
thank you :+1:

**Comment by mks0601** [comment]
I used `['400008', '400030', '400053', '400059']`.

**Comment by donguk-dev** [comment]
Thank you for your guidance !
