### ISSUE TITLE
What was the fitting procedure for MANO parameters?

### ISSUE THREAD

**Issue by pablovela5620** [facebookresearch/InterHand2.6M#20]
Would love to get a bit more info as to how you fit the MANO hand model to the hand. Was it a similar process to what was done in the FreiHand dataset (multiview loss function for 2d/3d/segmentation) or something different like the SPIN algorithm for full-body mesh estimation? I didn't see anything about a fitting procedure in the original paper. Thanks!

**Comment by mks0601** [comment]
That is a part of my ongoing CVPR work. I'll upload it on arxiv maybe right after cvpr submission (mid of Nov.).

**Comment by pablovela5620** [comment]
Understood, appreciate the info! Looking forward to seeing it

**Comment by mks0601** [comment]
Hi, my new work used to get the MANO parameters is available on [arxiv](https://arxiv.org/abs/2011.11232)

**Comment by pablovela5620** [comment]
Congrats on the submissions! I'd love to ask you some questions on the paper, but I don't know if this is the best place (or if I should wait for the code release on the neural annotator) please let me know. Again congrats, looks like this will solve alot of the current dataset generation problems!

**Comment by mks0601** [comment]
the codes will be available once it is accepted, so maybe you can ask questions by email?
