### ISSUE TITLE
Dataset ""transform** bug?

### ISSUE THREAD

**Issue by felixfuu** [facebookresearch/InterHand2.6M#23]
1、https://github.com/facebookresearch/InterHand2.6M/blob/master/common/base.py#L81
transforms.ToTensor(), img->[0, 1]
2、https://github.com/facebookresearch/InterHand2.6M/blob/master/data/InterHand2.6M/dataset.py#L139
img->[0, 1/255.] ?

**Comment by mks0601** [comment]
Did you check ToTensor normalizes floating tensors as well? As I remember, it only normalizes integer tensors, so the first stage does not normalize img to [0,1]

**Comment by felixfuu** [comment]
You are right, thank you for your reply.
