### ISSUE TITLE
Question about joints order

### ISSUE THREAD

**Issue by ahsan3803** [facebookresearch/InterHand2.6M#27]
@mks0601 what is the order of joints if we talk about only right hand? 
Can you confirm that order of joint is same as below?

![image](https://user-images.githubusercontent.com/58796370/99778262-6a8cfc00-2b4e-11eb-96f3-a9387befc446.png)

In above list where `00` is the joints closest to wrist and `03` is the finger tips

If order is not same as above list then what is the order of joints?

**Comment by mks0601** [comment]
Yes. Both left and right hands have the same joint order.

**Comment by ahsan3803** [comment]
@mks0601 I checked InterHand skeleton and seems that joints order is not same as below list 

![image](https://user-images.githubusercontent.com/58796370/99922793-5410bb80-2d6d-11eb-838f-447bd02dfb34.png)

Could you double check about right order?

**Comment by mks0601** [comment]
Oh where did you get this order? The joint order is defined in `annotations/skeleton.txt`.

```
# keypoint name, keypoint index, parent index
r_thumb4 0 1
r_thumb3 1 2
r_thumb2 2 3
r_thumb1 3 20
r_index4 4 5
r_index3 5 6
r_index2 6 7
r_index1 7 20
r_middle4 8 9
r_middle3 9 10
r_middle2 10 11
r_middle1 11 20
r_ring4 12 13
r_ring3 13 14
r_ring2 14 15
r_ring1 15 20
r_pinky4 16 17
r_pinky3 17 18
r_pinky2 18 19
r_pinky1 19 20
r_wrist 20 -1
l_thumb4 21 22
l_thumb3 22 23
l_thumb2 23 24
l_thumb1 24 41
l_index4 25 26
l_index3 26 27
l_index2 27 28
l_index1 28 41
l_middle4 29 30
l_middle3 30 31
l_middle2 31 32
l_middle1 32 41
l_ring4 33 34
l_ring3 34 35
l_ring2 35 36
l_ring1 36 41
l_pinky4 37 38
l_pinky3 38 39
l_pinky2 39 40
l_pinky1 40 41
l_wrist 41 -1
```

**Comment by ahsan3803** [comment]
@mks0601 I was trying to plot 3D hands using above order. Thanks for clarification.
