### ISSUE TITLE
When will the 30fps images be released?

### ISSUE THREAD

**Issue by wangjingbo1219** [facebookresearch/InterHand2.6M#28]
Hi
I would like to do some research on the video-based 3D hand pose estimation and I would like to know when will the 30 fps image will be released.
THX

**Comment by mks0601** [comment]
I'm waiting for FB's data inspection. I also do not know when they will finish the inspection :( I also hope 30 fps version would be available soon :(

**Comment by wangjingbo1219** [comment]
Patpat, thanks for your help : )
