### ISSUE TITLE
Error in extracting files from the InterHand2.6M.tar

### ISSUE THREAD

**Issue by shuyangyue** [facebookresearch/InterHand2.6M#3]
Hello! Thank you for releasing the great hand dataset. I downloaded all parts of the InterHand2.6M dataset. When I used the command: 
`cat InterHand2.6M.images.5.fps.v0.0.tar.parta* | tar -xvf - -i`
error occured:
> tar: Skipping to next header
> tar: Skipping to next header
> tar: Skipping to next header
> tar: Exiting with failure status due to previous errors

Is there anything wrong in the tar files?

**Comment by mks0601** [comment]
Hmm.. which OS are you using? The command works well on my Ubuntu 16.04 and 18.04 machines.

**Comment by Junwen-Huang** [comment]
Same error. OS: Ubuntu 16.04.6 LTS.
Besides, the structure of the ``InterHand2.6M_$DB_SPLIT_joint_3d.json`` is not the same as instructions.

**Comment by mks0601** [comment]
The structure of the `InterHand2.6M_$DB_SPLIT_joint_3d.json` is updated yesterday, as you can see in [here](https://mks0601.github.io/InterHand2.6M/)

**Comment by Junwen-Huang** [comment]
Thanks. Actually, I found it like:
InterHand2.6M_$DB_SPLIT_joint_3d.json
|-- str (capture id)
|    |-- str (frame idx): 42x3 list (3D joint coordinates in the world coordinate system.)
After I updated the json file, it is OK now.

**Comment by mks0601** [comment]
Yes I added several keys. Could you check you downloaded all InterHand2.6M.images.5.fps.v0.0.tar.partaa~u images?

**Comment by shuyangyue** [comment]
> Hmm.. which OS are you using? The command works well on my Ubuntu 16.04 and 18.04 machines.

The OS platform is 18.04.1. I downloaded all partaa~u. the size of my files on Ubuntu 18.04:

> 1945604	InterHand2.6M.images.5.fps.v0.0.tar.partaa
1945604	InterHand2.6M.images.5.fps.v0.0.tar.partab
1945604	InterHand2.6M.images.5.fps.v0.0.tar.partac
1944196	InterHand2.6M.images.5.fps.v0.0.tar.partad
1945604	InterHand2.6M.images.5.fps.v0.0.tar.partae
1945604	InterHand2.6M.images.5.fps.v0.0.tar.partaf
1945604	InterHand2.6M.images.5.fps.v0.0.tar.partag
1945604	InterHand2.6M.images.5.fps.v0.0.tar.partah
1945604	InterHand2.6M.images.5.fps.v0.0.tar.partai
1945604	InterHand2.6M.images.5.fps.v0.0.tar.partaj
1945604	InterHand2.6M.images.5.fps.v0.0.tar.partak
1945604	InterHand2.6M.images.5.fps.v0.0.tar.partal
1945604	InterHand2.6M.images.5.fps.v0.0.tar.partam
1945604	InterHand2.6M.images.5.fps.v0.0.tar.partan
1945604	InterHand2.6M.images.5.fps.v0.0.tar.partao
1945604	InterHand2.6M.images.5.fps.v0.0.tar.partap
1945604	InterHand2.6M.images.5.fps.v0.0.tar.partaq
1945604	InterHand2.6M.images.5.fps.v0.0.tar.partar
1945604	InterHand2.6M.images.5.fps.v0.0.tar.partas
1945604	InterHand2.6M.images.5.fps.v0.0.tar.partat
1583464	InterHand2.6M.images.5.fps.v0.0.tar.partau

I can't figure out which file is error. Could you provide the hash value of each file or share one compress file of the dataset

**Comment by mks0601** [comment]
Can you download files again from here?
https://drive.google.com/drive/folders/1I7j-yoyiu3EsXxaRasmuxcawBJu0rRvG?usp=sharing

**Comment by shuyangyue** [comment]
> Yes I added several keys. Could you check you downloaded all InterHand2.6M.images.5.fps.v0.0.tar.partaa~u images?

Sorry, It's my fault. I found the size of partaa~parat is  1945600k on Windows, the size of each file is same. But on Ubuntu, I found my 'partad' is smaller than other files. I download it agian, and solved. Thank you for  your rely

**Comment by shuyangyue** [comment]
> Yes I added several keys. Could you check you downloaded all InterHand2.6M.images.5.fps.v0.0.tar.partaa~u images?

Could you provide the hash value of each file?

**Comment by shuyangyue** [comment]
> > Yes I added several keys. Could you check you downloaded all InterHand2.6M.images.5.fps.v0.0.tar.partaa~u images?
> 
> Could you provide the hash value of each file?



> Yes I added several keys. Could you check you downloaded all InterHand2.6M.images.5.fps.v0.0.tar.partaa~u images?

ALl

**Comment by shuyangyue** [comment]
The size of all files is shown as bellow:

> 1945604	InterHand2.6M.images.5.fps.v0.0.tar.partaa
1945604	InterHand2.6M.images.5.fps.v0.0.tar.partab
1945604	InterHand2.6M.images.5.fps.v0.0.tar.partac
1945604	InterHand2.6M.images.5.fps.v0.0.tar.partad
1945604	InterHand2.6M.images.5.fps.v0.0.tar.partae
1945604	InterHand2.6M.images.5.fps.v0.0.tar.partaf
1945604	InterHand2.6M.images.5.fps.v0.0.tar.partag
1945604	InterHand2.6M.images.5.fps.v0.0.tar.partah
1945604	InterHand2.6M.images.5.fps.v0.0.tar.partai
1945604	InterHand2.6M.images.5.fps.v0.0.tar.partaj
1945604	InterHand2.6M.images.5.fps.v0.0.tar.partak
1945604	InterHand2.6M.images.5.fps.v0.0.tar.partal
1945604	InterHand2.6M.images.5.fps.v0.0.tar.partam
1945604	InterHand2.6M.images.5.fps.v0.0.tar.partan
1945604	InterHand2.6M.images.5.fps.v0.0.tar.partao
1945604	InterHand2.6M.images.5.fps.v0.0.tar.partap
1945604	InterHand2.6M.images.5.fps.v0.0.tar.partaq
1945604	InterHand2.6M.images.5.fps.v0.0.tar.partar
1945604	InterHand2.6M.images.5.fps.v0.0.tar.partas
1945604	InterHand2.6M.images.5.fps.v0.0.tar.partat
1583464	InterHand2.6M.images.5.fps.v0.0.tar.partau

There are two “tar: Skipping to next header” now, after I download the partad again.(my previous 'partad' is smaller than other file).

now the error are:

> tar: Skipping to next header
tar: Skipping to next header
tar: Exiting with failure status due to previous errors

Could you provide the hash value of each file that I can figure out which file is wrong

**Comment by mks0601** [comment]
```
56ef648917e1c802e1cbd9baed7ac0e5  InterHand2.6M.images.5.fps.v0.0.tar.partaa
287677daedfbb8dde556fcede5797aa3  InterHand2.6M.images.5.fps.v0.0.tar.partab
7fd1471883493fa9af4a90beaad6cb05  InterHand2.6M.images.5.fps.v0.0.tar.partac
d548e01dfaea1facf4c3f9215d5ce669  InterHand2.6M.images.5.fps.v0.0.tar.partad
8ac888fdf27474b485305c2b418d9144  InterHand2.6M.images.5.fps.v0.0.tar.partae
e845131769e185d2b091db07494b0849  InterHand2.6M.images.5.fps.v0.0.tar.partaf
534a5b8c6635470c068df370fd919955  InterHand2.6M.images.5.fps.v0.0.tar.partag
f5f8ef17a4f5a8400c7342f9dee18dc6  InterHand2.6M.images.5.fps.v0.0.tar.partah
4f4d71d8279f5a846f613f17cfae30eb  InterHand2.6M.images.5.fps.v0.0.tar.partai
08b59a6a4d12fbfcdb4f54ced8253812  InterHand2.6M.images.5.fps.v0.0.tar.partaj
5442b262d559349610c89909c6880878  InterHand2.6M.images.5.fps.v0.0.tar.partak
bf75fd9aab4fea01a33ad1c406407299  InterHand2.6M.images.5.fps.v0.0.tar.partal
e5d83e784a9fcd0d94d21efb54a2a29b  InterHand2.6M.images.5.fps.v0.0.tar.partam
53baeb9e42cc3c0d370ba1112e57387a  InterHand2.6M.images.5.fps.v0.0.tar.partan
732876e477d5bfda016072a9b59901e9  InterHand2.6M.images.5.fps.v0.0.tar.partao
1d16c22e24216ac57ff26990ee3f2762  InterHand2.6M.images.5.fps.v0.0.tar.partap
a325582aeab34bbe8f866e26cc5f6205  InterHand2.6M.images.5.fps.v0.0.tar.partaq
543b509084a116f7b941bc55c1e6644c  InterHand2.6M.images.5.fps.v0.0.tar.partar
ae2fdb2635928da4c52583f88f0126e7  InterHand2.6M.images.5.fps.v0.0.tar.partas
7e7040b35ab6da26ee722f1e953cc468  InterHand2.6M.images.5.fps.v0.0.tar.partat
fbf53aa75c971252f38066006ad99e8b  InterHand2.6M.images.5.fps.v0.0.tar.partau
```

**Comment by mks0601** [comment]
Those are md5sum hash values.

**Comment by shuyangyue** [comment]
> Those are md5sum hash values.

Thank you, I found my two files's md5sum hash values are different from yours. I'm downloading them now. I think it solves my problems

**Comment by Junwen-Huang** [comment]
> Yes I added several keys. Could you check you downloaded all InterHand2.6M.images.5.fps.v0.0.tar.partaa~u images?

I redownloaded those files and no error occur, so it may caused by disconnection when downloading. Thanks so much.

**Comment by zjhthu** [comment]
Hi, I download the 5fps dataset as instruction in this [page](https://mks0601.github.io/InterHand2.6M/), all the files has the same md5 as the provided [file](https://fb-baas-f32eacb9-8abb-11eb-b2b8-4857dd089e15.s3.amazonaws.com/InterHand2.6M/InterHand2.6M.images.5.fps.v1.0/InterHand2.6M.images.5.fps.v1.0.tar.CHECKSUM).
But I get error when unzipping these files, e.g., the last zip file InterHand2.6M.images.5.fps.v1.0.tar.partbr is only 18M. 

I find this issue provide another link in google drive, but has different md5. Which is the correct one?

**Comment by mks0601** [comment]
You can download the files from [here](https://mks0601.github.io/InterHand2.6M/).
How did you unzip the files? Did you run sh unzip.sh?

**Comment by zjhthu** [comment]
yes, I download files from there and run the unzip.sh, e.g., tar -xvf InterHand2.6M.images.5.fps.v1.0.tar.partbr, but got error.

I just check the md5 of the last file InterHand2.6M.images.5.fps.v1.0.tar.partbr, which is 861f35038ebddd998cbd91cf6cd750a9, the same as the provided md5 file.

**Comment by mks0601** [comment]
Could you give me the error message?

**Comment by zjhthu** [comment]
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors

**Comment by mks0601** [comment]
I guess you ran the wrong unzip command?
The unzip.sh has `cat InterHand2.6M.images.5.fps.v1.0.tar.part* | tar -xvf - -i`

**Comment by zjhthu** [comment]
Sorry ....

**Comment by mks0601** [comment]
:)
