### ISSUE TITLE
Mutli-view data.

### ISSUE THREAD

**Issue by penincillin** [facebookresearch/InterHand2.6M#37]
Hi,
Thanks for your great work and provide us this wonderful dataset !
I have a question about multi-data, can I determine the sample pose from the name of image.
For example, can I presume the following two images to have the same pose, since they only differ in `camera_id`. 
`Capture1/0287_pointingtowardsfeatures/cam410210/image67650.jpg` and
`Capture1/0287_pointingtowardsfeatures/cam410220/image67650.jpg`

**Comment by mks0601** [comment]
Hi,

Yes. They have exactly the same pose and taken at the same time step.
By the way, I read your paper FrankMocap, which seems work well on various images and videos.
Good luck to your ongoing project :)

**Comment by penincillin** [comment]
Thanks for answering and bringing us wonderful works like InterHand2.6M and RootNet :)
Good luck to your ongoing project, too :)
