### ISSUE TITLE
something wrong when read the  dataset

### ISSUE THREAD

**Issue by liwenssss** [facebookresearch/InterHand2.6M#4]
Hi, thanks for your work and your dataset.When I use your demo I meet the error:
```
joint_world = np.array(joints[str(capture_id)][str(frame_idx)]['world_coord'], dtype=np.float32)
TypeError: list indices must be integers or slices, not str
```
I download the annotation file "InterHand2.6M.annotations.5.fps.zip" and the image files allready.Do you know how to solve it  ? Is there any possible that I download the wrong files?

**Comment by mks0601** [comment]
Yes that file is updated several days ago. Could you download it again?

**Comment by liwenssss** [comment]
> Yes that file is updated several days ago. Could you download it again?

thank you, it is ok now^^
