### ISSUE TITLE
Mapping INTERHand joint to MANO joint order

### ISSUE THREAD

**Issue by joshuajano** [facebookresearch/InterHand2.6M#42]
Hi, this is really nice work.
I Have a question about this dataset. Based on my understanding, INTERHand26m joint order is different from MANO joint order. 
Do you have a plan to map the joint to the MANO version?
Thank you!

Best regards,

Joshua

**Comment by mks0601** [comment]
Yes, the joint order is different and that of our dataset is provided in skeleton.txt file.
That should've been considered in the initial release of this dataset, but I'm afraid changing the joint order after a while of dataset release can make people confusing :(

**Comment by joshuajano** [comment]
I see. If you have the mapping to MANO if you do not mind, can you share it with me through email? 
Thank you

**Comment by mks0601** [comment]
There are multiple MANO joint set. Which MANO joint set are you using? I think you can easily make the correspondence by comparing the joint name?

**Comment by joshuajano** [comment]
I see. Thank you!
