### ISSUE TITLE
shouldn't the `all` folder have the validation files also ?

### ISSUE THREAD

**Issue by MohamedAliRashad** [facebookresearch/InterHand2.6M#45]
It's kind of confusing to find the validation json files in `machine_annot` folder but not in the `all` folder, shouldn't it be also their or i miss-understood something ?

**Comment by mks0601** [comment]
As you can see Table 2 of the paper, there is only `machine_annot` in validation set.

**Comment by MohamedAliRashad** [comment]
@mks0601 isn't the `all` folder contain the best results from `machine_annot` and `human_annot` ?

**Comment by mks0601** [comment]
could you tell me which file is included in `machine_annot`, but not included in `all`?

**Comment by mks0601** [comment]
`all` is summation of `machine_annot` and `human_annot`.
As the validation set is only consists of `machine_annot` (no `human_annot`, there is no `all` for the validation set.

**Comment by MohamedAliRashad** [comment]
@mks0601 That doesn't make any sense.
`machine_annot` + no `human_annot` = `machine_annot` not `None`

**Comment by mks0601** [comment]
Hey, be careful  about your aggressive comment.
`machine_annot + no human_annot = machine_annot not None` <- I cannot get what you meant by this.

The validation set only consists of `machine_annot`.
There is no `human_annot` subset in the validation set.
So, `all` of validation set would be the same with `machine_annot` of the validation set.

**Comment by MohamedAliRashad** [comment]
I am sorry, i didn't mean any offense.

it has been very bad couple of days for me, thanks for your patience and kind answers.

**Comment by MohamedAliRashad** [comment]
I will be closing the issue
