### ISSUE TITLE
can not

### ISSUE THREAD

**Issue by MengHao666** [facebookresearch/InterHand2.6M#48]
Hi, thanks for such great work!

I fail to download this dataset, as the error like "Time limit of download  is exceeded!" occured.
Do u know ehat happened? Is there any solution?

all best,
Hao Meng

**Comment by mks0601** [comment]
![image](https://user-images.githubusercontent.com/13601723/114298883-7e340180-9af3-11eb-8868-fed7f24c594a.png)

Please read the instructions.

**Comment by MengHao666** [comment]
oh, i am not careful enough. 
Got it! Thanks!
