### ISSUE TITLE
Can you keep the results from v0.0?

### ISSUE THREAD

**Issue by zc-alexfan** [facebookresearch/InterHand2.6M#51]
Thanks for releasing the full dataset. I noticed that the results and the model from v0.0 dataset are no longer there. Is it possible to include those in the current README again? Because some of us might need to do some experiments during ICCV rebuttal.

**Comment by mks0601** [comment]
Sure.
The results are [here](https://github.com/facebookresearch/InterHand2.6M/releases/download/v1.0/InterNet.results.on.InterHand2.6M.v0.0.zip) and models are [here](https://github.com/facebookresearch/InterHand2.6M/releases/download/v1.0/InterNet.trained.on.InterHand2.6M.v0.0.zip).
