### ISSUE TITLE
InterHand2.6M_XXX_MANO.json Discard or not?

### ISSUE THREAD

**Issue by Gzzgz** [facebookresearch/InterHand2.6M#52]
all of the InterHand2.6M_XXX_MANO.json are replaced by InterHand2.6M_XXX_MANO_NeuralAnnot.json ?  THX

**Comment by mks0601** [comment]
Hi, yes all json files are updated.
The new version is better than the old ones, so you can just discard the old ones.

**Comment by Gzzgz** [comment]
OK THX

But I find InterHand2.6M_XXX_MANO_NeuralAnnot.json is smaller than InterHand2.6M_XXX_MANO.json very much. Is there a lot of missing data?

**Comment by mks0601** [comment]
I don't think so.. when did you download the json files? As written in the README, the json files got smaller in 2020.11.26

**Comment by Gzzgz** [comment]
OK , I think so. the mano labels count like that:
all:
train:1340326
test:848297
val:379947

I'm just curious about how it's getting smaller. Good Job!

**Comment by mks0601** [comment]
Before the update, there were MANO parameters for each camera view and for each time step, which make the number of MANO parameters extremely large. Instead, the updated version has a single MANO parameter for each time step (note that 'each camera view' is removed), which can be transformed to each camera view.

**Comment by Gzzgz** [comment]
OK THX!
