### ISSUE TITLE
what is "smplx_path" indeed?

### ISSUE THREAD

**Issue by MengHao666** [facebookresearch/InterHand2.6M#53]
You said `Set smplx_path in render.py` in section of  `MANO mesh rendering demo`, but what is smplx_path indeed?

**Comment by Wiikk** [comment]
Hi, I meet the same question, could you please tell me how to fix this?

**Comment by MengHao666** [comment]
> Hi, I meet the same question, could you please tell me how to fix this?

 the path of smplx model

**Comment by Wiikk** [comment]
thanks!
