### ISSUE TITLE
Missing skeleton.txt for RHD and STB

### ISSUE THREAD

**Issue by dihuangdh** [facebookresearch/InterHand2.6M#6]
Hi, @mks0601 

Thanks for your awesome work!

Is the skeleton.txt file for RHD and STB missing ? Could you please add it ?

**Comment by mks0601** [comment]
Added! You can download from README or here
RHD: https://github.com/facebookresearch/InterHand2.6M/releases/download/v0.0/RHD.annotations.zip
STB: https://github.com/facebookresearch/InterHand2.6M/releases/download/v0.0/STB.annotations.zip
