### ISSUE TITLE
about Train/Test settings

### ISSUE THREAD

**Issue by zqq-judy** [facebookresearch/InterHand2.6M#62]
Hello!
In the results of Table 3 in the paper (training set: SH+IH (ours), SH MPJPE: 12.16, IH MPJPE: 16.02), do you use all the images(1361K) in the train dataset, including gray images? And, testing in 849K images?  Because I see  gray images in the dataset. For example, the camera id starts with cam41.
Thanks for your reply.

**Comment by mks0601** [comment]
Yes. All images including gray images are used for the training and testing.

**Comment by zqq-judy** [comment]
On the test dataset (all images 5fps) of V1.0，I used your pre-trained model snapshot_20.pth.tar (5fps V0.0). But the result is not good.

MPJPE for all hand sequences: 78.63
MPJPE for single hand sequences: 88.65
MPJPE for interacting hand sequences: 69.90

Why is this? Is it because of the version of the dataset?

**Comment by mks0601** [comment]
I think so.. I'll release a model trained on v1.0 soon.

**Comment by mks0601** [comment]
Meanwhile, you can test on `human_annot`. The performance on `human_annot` is very similar to those of the paper.

**Comment by zqq-judy** [comment]
The result of `human_annot`(v1.0) is :

MPJPE for all hand sequences: 74.74
MPJPE for single hand sequences: 77.17
MPJPE for interacting hand sequences: 73.92

**Comment by mks0601** [comment]
I think you have done something wrong. My human_annot performance (v1.0) is very similar to that of the paper. I just ran the testing. About 5 mins ago?

**Comment by zqq-judy** [comment]
I re-downloaded the code on GitHub, and the test dataset is `  human_annot ` (v1.0downloaded in April), the pre-trained model downloaded ` [Trained on InterHand2.6M 5 fps (v0.0)]`， and root_net downloaded `[ Output on InterHand2.6M]`. I only changed the path where the dataset was loaded, and the other codes were unchanged. But the result obtained is still the result of the above comment (MPJPE for all hand sequences: 74). 

I am a little confused.

**Comment by mks0601** [comment]
Could you change `trans_test` in main/config.py to gt?
This guy also got good results on human_annot.
https://github.com/facebookresearch/InterHand2.6M/issues/59#issuecomment-849185485

**Comment by mks0601** [comment]
I got the reason. the bboxs in rootnet results are not downsampled :( 
Could you change [this line](https://github.com/facebookresearch/InterHand2.6M/blob/0e4641582758fd77ef244b94c0775da67b1844cc/data/InterHand2.6M/dataset.py#L88) to bbox = np.array(rootnet_result[str(aid)]['bbox'],dtype=np.float32) / 2.? 
I'll also update the rootnet results soon.

**Comment by mks0601** [comment]
![image](https://user-images.githubusercontent.com/13601723/121441040-020b4c80-c9c4-11eb-8a34-3d03125cce95.png)

This is what I got when downsampled the bbox following the above comment.

**Comment by zqq-judy** [comment]
Thank you for your patience to help me solve the problem. I have tested the results similar to those in the paper. Thank you very much.

**Comment by mks0601** [comment]
You can download the rootnet results from [here](https://drive.google.com/drive/u/1/folders/1DRUVTPg8-6grwr1qwquFi5Anwmxl7y0S) and use the boxs from them without downsizing, i.e., you do not have to change [this line](https://github.com/facebookresearch/InterHand2.6M/blob/0e4641582758fd77ef244b94c0775da67b1844cc/data/InterHand2.6M/dataset.py#L88) if you download the rootnet results again. Thanks!

**Comment by mks0601** [comment]
The model trained on v1.0 is available in [here](https://drive.google.com/drive/u/1/folders/143sqUHLq3stQTvJdV1YdBivnkM1bfAJE)

**Comment by zqq-judy** [comment]
Ok. Thanks.
