### ISSUE TITLE
the annot_id of newest rootnet results(6.10) is incorrect

### ISSUE THREAD

**Issue by 674106399** [facebookresearch/InterHand2.6M#63]
I got the error from dataset.py

bbox = np.array(rootnet_result[str(aid)]['bbox'],dtype=np.float32)

KeyError: '75650'

then I double checked the rootnet_interhand2.6m_output_val.json

I found that

[{'annot_id': 75648,
  'bbox': [-41.625, -57.333282470703125, 416.25, 416.25],
  'abs_depth': [1198.4647216796875, 1103.005126953125],
  'root_valid': [0.0, 0.0]},
 {'annot_id': 75649,
  'bbox': [279.90289306640625,
   24.204498291015625,
   100.38922119140625,
   100.38922119140625],
  'abs_depth': [1224.00341796875, 1226.8614501953125],
  'root_valid': [0.0, 0.0]},
 {'annot_id': 75651,
  'bbox': [-70.4109115600586,
   72.7760009765625,
   151.77374267578125,
   151.77374267578125],
  'abs_depth': [1122.958740234375, 1113.6966552734375],
  'root_valid': [1.0, 0.0]}]

the annot_id 75650 is missing.

**Comment by mks0601** [comment]
Are you using 30fps dataset for the training? There is another rootnet result for the 30fps version.

**Comment by 674106399** [comment]
> Are you using 30fps dataset for the training? There is another rootnet result for the 30fps version.

No, I'm using 5fps dataset. I download your newest rootnet json today. (double-checked again just now)

**Comment by mks0601** [comment]
![image](https://user-images.githubusercontent.com/13601723/121652774-f5c3e400-cad6-11eb-86d7-73665a25c959.png)

**Comment by mks0601** [comment]
I have no problem. Could you check your setting?

**Comment by 674106399** [comment]
> I have no problem. Could you check your setting?

Sorry, are you sure that your code is the same as current master branch?

I tried that clone a new master branch and run the code, but get the same error. I'm pretty sure the data is the newest. And I don't have any setting.

![POPO20210611-163654](https://user-images.githubusercontent.com/13503330/121660089-8699c000-cad5-11eb-91e3-6b0d9cda0435.png)

**Comment by 674106399** [comment]
> I have no problem. Could you check your setting?

Sorry, are you sure that your code is the same as the current master branch?

I cloned this repo and downloaded data again, and still got the error. 
![POPO20210611-163654](https://user-images.githubusercontent.com/13503330/121666944-63264380-cadc-11eb-95a4-19d1443887ca.png)

**Comment by mks0601** [comment]
I guess you are using different annotation file. InterHand2.6M_val_data.json does not have annotation with annotation_id == 75650.

**Comment by 674106399** [comment]
I guess it's a bug of google driver. The file is correct right now. Thanks for your kind help!
