### ISSUE TITLE
How's the data organized differently from v0.0?

### ISSUE THREAD

**Issue by zc-alexfan** [facebookresearch/InterHand2.6M#68]
I have been using v0.0 and recently need to adapt to the new v1.0 version. The naming convention for the annotation files 
seems to have changed a lot. My code is expecting the different splits for train, val, test in terms of `all`, `machine_annot`, `human_annot`. However, the current annotation look like the following:
```
train ls
InterHand2.6M_train_MANO_NeuralAnnot.json  InterHand2.6M_train_camera.json  InterHand2.6M_train_data.json  InterHand2.6M_train_joint_3d.json

val ls
InterHand2.6M_val_MANO_NeuralAnnot.json  InterHand2.6M_val_camera.json  InterHand2.6M_val_data.json  InterHand2.6M_val_joint_3d.json

test ls
InterHand2.6M_test_MANO_NeuralAnnot.json  InterHand2.6M_test_camera.json  InterHand2.6M_test_data.json  InterHand2.6M_test_joint_3d.json
```
Are they all the `all` split? Or how do I find the `machine_annot`, and `human_annot`?

**Comment by mks0601** [comment]
Hi,

As many people got confused between all/machine_annot/human_annot and train/test/val, I've decided to provide only all split.
So, the question to your answer is : yes. all json files are `all` split. Do you want `machine_annot` and `human_annot`?

**Comment by zc-alexfan** [comment]
I see. Do you also have `machine_annot` and `human_annot`? 

Another question: for 5 FPS, the v1.0 version differs from v0.0 in terms of number of images? I ran my experiments for my submission using v0.0. I guess I need to rerun them on v1.0.

**Comment by mks0601** [comment]
I can provide annotation ids of `machine_annot` and `human_annot` so that you can use them from `all`.
In both 5 and 30fps, v1.0 provides full images as written in [here](https://github.com/facebookresearch/InterHand2.6M#news). v0.0 has only half of full images.

**Comment by zc-alexfan** [comment]
That works. Thanks

**Comment by mks0601** [comment]
Here are links
5fps: https://drive.google.com/drive/folders/1iDI_wRkngB374IksPbEB_OeoO1CJsedV?usp=sharing
30fps: https://drive.google.com/drive/folders/1bCqioHhiXiB3Mva1hbBENeY4vZjtfW62?usp=sharing

**Comment by wbhu** [comment]
Hi @mks0601,

Thanks for your great work. I also need the split for machine_annot and human_annot. But I only found the 'train' and 'test' splits for machine_annot and human_annot, while the original annot has 'train', 'val', and 'test' splits. What is the correspondence?

Thanks

**Comment by mks0601** [comment]
Hi,

Actually, `val` is defined only for machine_annot.
The provided `val` in [here](https://drive.google.com/drive/folders/1pWXhdfaka-J0fSAze0MsajN0VpZ8e8tO?usp=sharing) and [here](https://drive.google.com/drive/folders/1ySGf0dEmEV0s7v13pXZM_gLFujGRdO70?usp=sharing) are from machine_annot.

**Comment by wbhu** [comment]
got it, thanks
