### ISSUE TITLE
About 30fps download question

### ISSUE THREAD

**Issue by sakura2233565548** [facebookresearch/InterHand2.6M#69]
Firstly, appreciate for Interhand2.6M dataset released, but when I run download script for 30fps,
wget https://fb-baas-f32eacb9-8abb-11eb-b2b8-4857dd089e15.s3.amazonaws.com/InterHand2.6M/InterHand2.6M.images.30.fps.v1.0/InterHand2.6M.images.30.fps.v1.0/unzip.sh
I got a error for server 403 forbidden~ 
Could you help me resolve this issue?

**Comment by mks0601** [comment]
Oh my mistake. I modified the download link. I mistakenly inserted another 'InterHand2.6M.images.30.fps.v1.0' in the link :(
Here is the correct one: wget https://fb-baas-f32eacb9-8abb-11eb-b2b8-4857dd089e15.s3.amazonaws.com/InterHand2.6M/InterHand2.6M.images.30.fps.v1.0/unzip.sh

**Comment by sakura2233565548** [comment]
Thank you a lot!
