### ISSUE TITLE
Function :  transform_input_to_output_space

### ISSUE THREAD

**Issue by linkinSimon** [facebookresearch/InterHand2.6M#70]
Hi, @mks0601,

Thanks for sharing this amazing project !!
May I ask some questions about the transform_input_to_output_space function?

1. Why set bbox_3d_size = 400 and bbox_3d_size_root  = 400 in (<a href="https://github.com/facebookresearch/InterHand2.6M/blob/2b8061d2c8e762aa6fcb8e6f5d18f8a9e83bfd0c/main/config.py#L23">link src</a>), what's the meaning of the two?

2. Why preprocess the ground truth relative depth into this domain
    joint_coord[:,2] = (joint_coord[:,2] / (cfg.bbox_3d_size/2) + 1)/2. * cfg.output_hm_shape[0] (<a href="https://github.com/facebookresearch/InterHand2.6M/blob/2b8061d2c8e762aa6fcb8e6f5d18f8a9e83bfd0c/common/utils/preprocessing.py#L105">link src</a>), is this good for converge?

Is there any explanation in this paper or this repository that I missed?

Really thanks for your time and help!!

**Comment by mks0601** [comment]
1. The size of a 3d box of a hand is 400 mm.
2. To make it into a heatmap space.
Thanks!

**Comment by linkinSimon** [comment]
Oh, I got it. 

1. bbox_3d_size = 400 and bbox_3d_size_root = 400 is assuming a hand relative depth is within 400mm if the root lies at the middle 200 mm.

2. joint_coord[:,2] = (joint_coord[:,2] / (cfg.bbox_3d_size/2) + 1)/2. * cfg.output_hm_shape[0] <a href="https://github.com/facebookresearch/InterHand2.6M/blob/2b8061d2c8e762aa6fcb8e6f5d18f8a9e83bfd0c/common/utils/preprocessing.py#L105">link src</a> is trying to map the relative depth to 0-64 space like the 2D heatmaps with the root joint lies at the middle 32.

A huge thanks for the explanation !!

**Comment by ZYX-MLer** [comment]
> * The size of a 3d box of a hand is 400 mm.
> * To make it into a heatmap space.
>   Thanks!

How do you decide the value of bbox_3d_size? The largest value in the dataset?
If i training the model using my own dataset, how to set bbox_3d_size?

thanks

Best wishes

**Comment by mks0601** [comment]
Just based on prior knowledge about human scales. The value does not belong to specific datasets
