### ISSUE TITLE
30 FPS v1 results

### ISSUE THREAD

**Issue by zc-alexfan** [facebookresearch/InterHand2.6M#71]
Hi,

In your paper it says "All reported frame numbers and experimental results in the paper are from the 5 fps configuration."

Do you have the 30 fps results from v1? I tried to find it but couldn't. Maybe I missed something.

**Comment by mks0601** [comment]
No I don't have results on 30fps split :(

**Comment by zc-alexfan** [comment]
Ah, I see. Just to confirm. There is no model pretrained on 30fps provided. Neither the results?

**Comment by mks0601** [comment]
No pre-trained model and no results.
We are internally developing a model for 30fps video.
