### ISSUE TITLE
Incorrect poses

### ISSUE THREAD

**Issue by anjugopinath** [facebookresearch/InterHand2.6M#72]
Hi,

I gave 3 inputs.
But, I am not getting proper poses for any of them.

Input 1:
![image](https://user-images.githubusercontent.com/4654298/127381358-f6b5fc40-6421-4ef3-9885-c336071c45ba.png)

Output 1:
![image](https://user-images.githubusercontent.com/4654298/127381509-bdacfb1e-55d2-43c5-9369-9b1d3b8c3cc5.png)

Input 2:
![image](https://user-images.githubusercontent.com/4654298/127381717-a02242c8-4562-42ad-97af-4913a4ad991c.png)

Output 2:
![image](https://user-images.githubusercontent.com/4654298/127381777-e4612c7f-b881-4b03-87bd-38b05f996686.png)

Input 3:
![image](https://user-images.githubusercontent.com/4654298/127382304-f271025d-d586-4b57-ab52-79c8bb8bf0a5.png)

Output 3:
![image](https://user-images.githubusercontent.com/4654298/127382433-fae3166b-a36b-4741-828e-982e6842e705.png)

**Comment by mks0601** [comment]
Hi, a model trained solely on our dataset does not generalize well to in-the-wild images as image appearance domain is quite different. Generalization to in-the-wild images is one of my ongoing project.

**Comment by anjugopinath** [comment]
Thank You for your reply.
I want to train it on another dataset. How do I determine the bounding boxes?

**Comment by mks0601** [comment]
Hand box detection is also work in progress in my ongoing project.

**Comment by anjugopinath** [comment]
May I know when it will be released please? I wanted to work on it asap. Hence, I was looking for other options.

**Comment by mks0601** [comment]
I guess it will not be available soon

**Comment by anjugopinath** [comment]
Okay. Thank You.
