### ISSUE TITLE
Hand masks

### ISSUE THREAD

**Issue by rohitdavas** [facebookresearch/InterHand2.6M#73]
Hi, 

Most of the background in your dataset is dark. ( correct ? ) I was wondering if the hand masks are available so that we can use random backgrounds. 

I have created approximate masks. It would be good if you guys have the masks with the dataset.

**Comment by mks0601** [comment]
We don't have masks, but the masks can be obtained by projecting meshes.

**Comment by rohitdavas** [comment]
Thanks. Could you please explain more ? I don't see meshes directly in the dataset. if you could give some pointers.

**Comment by mks0601** [comment]
https://github.com/facebookresearch/InterHand2.6M#mano-mesh-rendering-demo

**Comment by rohitdavas** [comment]
Thanks. However due to license restrictions I cannot use SIMPLX and MANO. Is there any other way ?

**Comment by mks0601** [comment]
Sorry. I have no idea about license-free hand models

**Comment by rohitdavas** [comment]
Thanks. Please comment back in case something comes into your mind.
