### ISSUE TITLE
Trained network checkpoints archives don't work

### ISSUE THREAD

**Issue by Pwyllugh93** [facebookresearch/InterHand2.6M#80]
Hi,
I downloaded the archives 

[Trained on InterHand2.6M 5 fps (v1.0)]
[Trained on STB]
[Trained on RHD]

from google drive on both windows and ubuntu and under no operating system I'm able to unzip or open the archives. Under windows it says that the files are no archives and cannot be unzipped and under ubuntu it says that the header is damaged. I googled the error messages and it said that the damage is not repairable. Unfortunately, I'm unable to access the exact error message right now. 
Are other people able to download the network checkpoints?

**Comment by mks0601** [comment]
They are not a zipped ones. Do not unzip and just use them.

**Comment by Pwyllugh93** [comment]
Thank you very much for your quick reply! Do you mean I just remove the .tar ending in windows by renaming the file? The same under ubuntu?

**Comment by mks0601** [comment]
Do not anything and just use pth.tar. Thst would work.

**Comment by Pwyllugh93** [comment]
Oh, I've never encountered that, so thank you for clarifying that and for your quick help :)
