### ISSUE TITLE
Questions about the evaluation metrics

### ISSUE THREAD

**Issue by Aegis923** [facebookresearch/InterHand2.6M#82]
Hi, I have reproduced your paper and obtained similar results as mentioned in the paper. Here I have a few questions about the evaluation metrics you choose for different dataset.
In your paper, "MPJPE is defined as a Euclidean distance (mm) between predicted and groundtruth 3D joint locations after root joint alignment,EPE is defined as a mean Euclidean distance (mm) between the predicted and ground-truth 3D hand pose after root joint alignment."  But I can’t understand the difference between the two metrics.
When I reproduced your code, I found that the output of the STB and RHP datasets are both measured by MPJPE. Does it mean that the two metrics are algorithmically similar or can be equivalently substituted?
Still, I have consulted many documents, the expression of mean EPE does not mention root joint  alignment (it may be my omission).
I would be very grateful if you can resolve my doubts. I'm looking forward to your reply.

**Comment by mks0601** [comment]
MPJPE and EPE are the same metrics. MPJPE is widely used in 3D human body pose estimation and I borrowed that name. EPE is used by several 3D hand pose estimation methods on STB and RHD. I just borrowed that name. I'd like to call that metric as MPJPE as that name is more widely used.

**Comment by Aegis923** [comment]
I understand. Thank you for your reply!
