### ISSUE TITLE
Why  are the bbox of the rootnet outputs the same as the gt annotation in val set and test set?

### ISSUE THREAD

**Issue by MengHao666** [facebookresearch/InterHand2.6M#91]
I am so confused about that. Could you tell me the reason?

**Comment by mks0601** [comment]
RootNet does not predict bboxes. It predicts only root joint depths from a cropped hand image, and GT bboxes are used to prepare inputs of RootNet.

**Comment by MengHao666** [comment]
> e json files are GT bboxes, used to prepare inputs of RootNet.

Oh, thanks for quick response. So all the bounding box used here are from GT annotations.
