### ISSUE TITLE
about 'J_regressor_mano_ih26m.npy'

### ISSUE THREAD

**Issue by abtiiin** [facebookresearch/InterHand2.6M#92]
Hi @mks0601 

Thanks for your great work,
Is `J_regressor_mano_ih26m.npy` identical  to  a joint regressor in `smplx.MANO` ?
https://github.com/facebookresearch/InterHand2.6M/blob/2b8061d2c8e762aa6fcb8e6f5d18f8a9e83bfd0c/tool/MANO_world_to_camera/convert.py#L33

**Comment by mks0601** [comment]
The joint regressor in MANO does not produce fingertips, so I manually added them. Also, the joint order is different.

**Comment by abtiiin** [comment]
I have used `manopth` [https://github.com/hassony2/manopth](url) which has assumed regressing the fingertips too and  then I reordered the joints.
I was wondering would that be identical to your regressor (I mean weights to interpolate joints)?

**Comment by mks0601** [comment]
Weights are the same, but the joint order is different.
