### ISSUE TITLE
why are bounding boxes of rootnet outputs same with that of annotations in machine_train branch.

### ISSUE THREAD

**Issue by MengHao666** [facebookresearch/InterHand2.6M#94]
I found the bbox [here](https://github.com/facebookresearch/InterHand2.6M/blob/2b8061d2c8e762aa6fcb8e6f5d18f8a9e83bfd0c/data/InterHand2.6M/dataset.py#L88l) is ame with the bbox [here](https://github.com/facebookresearch/InterHand2.6M/blob/2b8061d2c8e762aa6fcb8e6f5d18f8a9e83bfd0c/data/InterHand2.6M/dataset.py#L93). Could you give some explainantions?

**Comment by MengHao666** [comment]
Could anyone here answer my question?

**Comment by mks0601** [comment]
RootNet predicts absolute 3D wrist location in the camera-centered coordinate system from a cropped hand image.
To crop the hand image, GT bbox is used.
That is why both have the same GT bboxes.

**Comment by MengHao666** [comment]
> RootNet predicts absolute 3D wrist location in the camera-centered coordinate system from a cropped hand image. To crop the hand image, GT bbox is used. That is why both have the same GT bboxes.

Got it! Thanks for kind reply!
