### ISSUE TITLE
MANO or SMPLX ?

### ISSUE THREAD

**Issue by zeakey** [facebookresearch/InterHand2.6M#96]
I  input the 48D pose parameters in your dataset to a  MANO model <https://github.com/otaheri/MANO> to construct 3d mesh. However, hand shape is quit weird:

![1641987917(1)](https://user-images.githubusercontent.com/6763078/149134532-63d4b2e2-c3bd-4d69-9632-5cd1e3e69d4f.png)

In your code <https://github.com/facebookresearch/InterHand2.6M/blob/2b8061d2c8e762aa6fcb8e6f5d18f8a9e83bfd0c/tool/MANO_world_to_camera/convert.py> it seems that you are using SMPLX, a predecessor of MANO, not MANO for hand mesh construction.

So what should I use if I want to construct 3D mesh using your pose parameters ?

**Comment by mks0601** [comment]
'smplx' contains all 3D human models including smpl, smplx, mano, and flame. The example is using only mano. Maybe you are missing 'flat_hand_mean=False'

**Comment by zeakey** [comment]
I see.  Setting `flat_hand_mean=False` solved my problem.
