### ISSUE TITLE
Convert 3d coordinate to 2d?

### ISSUE THREAD

**Issue by quangdaist123** [facebookresearch/InterHand2.6M#97]
I want to create 2d coordinate of keyjoints for pretraining purspose on the dataset.
Is this possible? If so, how can I do it? 
Thanks!

**Comment by mks0601** [comment]
https://github.com/facebookresearch/InterHand2.6M/blob/2b8061d2c8e762aa6fcb8e6f5d18f8a9e83bfd0c/data/InterHand2.6M/dataset.py#L78

**Comment by quangdaist123** [comment]
Thank you very much! Have a nice day!
