### ISSUE TITLE
about MANO pose parameter

### ISSUE THREAD

**Issue by llpspark** [facebookresearch/InterHand2.6M#98]
Hi , when I use the MANO param file, I found that the MANO pose parameter is base on MEAN pose parameter(
<img width="650" alt="屏幕快照 2022-01-19 下午2 38 42" src="https://user-images.githubusercontent.com/20918669/150077616-49337645-e2eb-49a2-9a9b-bc785108def9.png">
),  and I wonder to know the MEAN pose parameter was, so that I convert it to based on flat pose param, thank u.

**Comment by mks0601** [comment]
Download mano .pkl file and you may find `hands_mean`

**Comment by llpspark** [comment]
> Download mano .pkl file and you may find `hands_mean`

thank you very much.

**Comment by Maradowei** [comment]
Hi, I want to transform a set of points into the axis-angle representation, but I don't understand what is the axis-angle representation, thank you.

**Comment by mks0601** [comment]
You can't directly transform 3D positions to 3D rotations as there is ambiguity. For example, you can image twisting your wrist while maintaining the same location.
